//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFootWeb.BigfootWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://www.tubri.org/museum/webservices", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tubri.org/museum/webservices", ConfigurationName="BigfootWS.BigfootSoap")]
    public interface BigfootSoap {
        
        // CODEGEN: Generating message contract since element name sp from namespace http://www.tubri.org/museum/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tubri.org/museum/webservices/GenerateFootprint", ReplyAction="*")]
        BigFootWeb.BigfootWS.GenerateFootprintResponse GenerateFootprint(BigFootWeb.BigfootWS.GenerateFootprintRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateFootprintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateFootprint", Namespace="http://www.tubri.org/museum/webservices", Order=0)]
        public BigFootWeb.BigfootWS.GenerateFootprintRequestBody Body;
        
        public GenerateFootprintRequest() {
        }
        
        public GenerateFootprintRequest(BigFootWeb.BigfootWS.GenerateFootprintRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tubri.org/museum/webservices")]
    public partial class GenerateFootprintRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public GenerateFootprintRequestBody() {
        }
        
        public GenerateFootprintRequestBody(string sp, string key) {
            this.sp = sp;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateFootprintResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateFootprintResponse", Namespace="http://www.tubri.org/museum/webservices", Order=0)]
        public BigFootWeb.BigfootWS.GenerateFootprintResponseBody Body;
        
        public GenerateFootprintResponse() {
        }
        
        public GenerateFootprintResponse(BigFootWeb.BigfootWS.GenerateFootprintResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tubri.org/museum/webservices")]
    public partial class GenerateFootprintResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BigFootWeb.BigfootWS.ArrayOfAnyType GenerateFootprintResult;
        
        public GenerateFootprintResponseBody() {
        }
        
        public GenerateFootprintResponseBody(BigFootWeb.BigfootWS.ArrayOfAnyType GenerateFootprintResult) {
            this.GenerateFootprintResult = GenerateFootprintResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BigfootSoapChannel : BigFootWeb.BigfootWS.BigfootSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BigfootSoapClient : System.ServiceModel.ClientBase<BigFootWeb.BigfootWS.BigfootSoap>, BigFootWeb.BigfootWS.BigfootSoap {
        
        public BigfootSoapClient() {
        }
        
        public BigfootSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BigfootSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BigfootSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BigfootSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BigFootWeb.BigfootWS.GenerateFootprintResponse BigFootWeb.BigfootWS.BigfootSoap.GenerateFootprint(BigFootWeb.BigfootWS.GenerateFootprintRequest request) {
            return base.Channel.GenerateFootprint(request);
        }
        
        public BigFootWeb.BigfootWS.ArrayOfAnyType GenerateFootprint(string sp, string key) {
            BigFootWeb.BigfootWS.GenerateFootprintRequest inValue = new BigFootWeb.BigfootWS.GenerateFootprintRequest();
            inValue.Body = new BigFootWeb.BigfootWS.GenerateFootprintRequestBody();
            inValue.Body.sp = sp;
            inValue.Body.key = key;
            BigFootWeb.BigfootWS.GenerateFootprintResponse retVal = ((BigFootWeb.BigfootWS.BigfootSoap)(this)).GenerateFootprint(inValue);
            return retVal.Body.GenerateFootprintResult;
        }
    }
}
